name: "Build and Push to GHCR"
on:
  push:
    branches:
      - main

env:
  working-directroy: ./

jobs:
  GHCR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
            docker build -f ./Dockerfile.frontend --tag ghcr.io/yohann30elias/counter-app-frontend:latest .
            docker build -f ./Dockerfile.backend --tag ghcr.io/yohann30elias/counter-app-backend:latest .
            docker push ghcr.io/yohann30elias/counter-app-frontend:latest
            docker push ghcr.io/yohann30elias/counter-app-backend:latest
